
# Github insists we set a markdown interpereter that is not the default
#markdown: redcarpet	# has bugs
markdown: kramdown	# github's suggestion

# This is the full set of plugins that GitHub supports
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - jemoji

# This is going to be a lot easier later...
# Must be set
theme_chain: 
  # Do local site stuff here, empty by default, masks all
  - local
  # Regular themes, need to pick right base below per comments
  # Needs Bootstrap3
  #- jekb
  # No base needed
  #- octo
  # Needs Foundation5
  - octolost
  # Base themes from here to core pick what's needed
  #- bootstrap2
  #- bootstrap3
  - foundation5
  # Always have core.
  - core

icon_set: dr

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
# Must not have trailing slash, IE: '/project/'
#root: /
root: http://jhohertz.github.io/dr-henry

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use root_url to make the urls
# Links in your website should always be prefixed with {{ root_url }}
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://jhohertz.github.io/dr-henry

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
# Until we have category landings established, this pattern doesn't suit well
#permalink: /:categories/:year/:month/:day/:title 
permalink: /blog/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

# Pagination, affects both front and archive paging
paginate: 10          # Posts per page on the blog index
paginate_path: "blog/:num"

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
# doesn't seem to work as documented. doing our own search/split for this.
#excerpt_seperator: "<!--fold-->"


# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Dr. Henry
subtitle : Jekyll transformation for your GitHub Pages... pages.
author :
  name : Joe Hohertz
  email : jhohertz@gmail.com
  github : jhohertz
  twitter : joehohertz

# Recent posts aside limit
recent_posts: 5

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.

blog_index_asides: [asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
# post_asides:
# page_asides:

simple_search: https://www.google.com/search
